repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: make ruff_check
        language: system
        pass_filenames: false
      - id: black
        name: black
        entry: make black_check
        language: system
        pass_filenames: false
      - id: tomlsort
        name: tomlsort
        entry: make tomlsort_check
        language: system
        pass_filenames: false
      - id: paracelsus
        name: paracelsus
        entry: make paracelsus_check
        language: system
        pass_filenames: false
