services:
  www:
    build:
      dockerfile: ./dockerfile.www
    volumes:
      - "./fastapi_snowflake_challenge:/app/fastapi_snowflake_challenge"
      - "./db:/app/db"
      - "./docker/www/prestart.sh:/app/prestart.sh"
    ports:
      - "80:80"
    environment:
      IS_DEV: true
      RELOAD: true
      DATABASE_URL: postgresql://main:main12345@db/main
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: main12345
      POSTGRES_USER: main
      POSTGRES_DB: main
