ARG PYTHON_VERSION=3.12
FROM ghcr.io/multi-py/python-uvicorn:py${PYTHON_VERSION}-slim-LATEST

ENV APP_MODULE=fastapi_snowflake_challenge.www:app

COPY requirements.txt /requirements.txt
COPY requirements-dev.txt /requirements-dev.txt
RUN pip install --no-cache-dir -r /requirements.txt -r /requirements-dev.txt
RUN apt-get update && apt-get install -y netcat-traditional && rm -rf /var/lib/apt/lists/*

COPY ./docker/www/prestart.sh /app/prestart.sh
COPY ./ /app
